Structural changes and adding information.
xournalpp/xournalpp.github.io pull request #25
Opened 2021-01-08 22:10 UTC by Wisehh

Changes made:

- Creation of a new section 'Tools and Editing':
  - The previous 'Tools and Editing' file is divided into multiple subsections (Eraser tool, Pen and Higlighter tools and LaTeX tool) that facilitate access to documentation on a specific tool. Additionally it lightens the content of the section since some tools have a very extensive documentation.
  - The documentation of 'Selection and Snapping tools' is added

- Creation of a new 'Plugins' section:
  - The previous Plugins file is divided into two new sections that facilitate punctual search, resulting in a subsection that documents the creation of plugins and another that talks about Notable Plugins (with an invitation to readers to enrich said subsection).

- Add information in 'Configuration':
  - Proposal for the structure of the section, where each section of the 'Preferences' menu corresponds to a subtitle with its respective documentation (perhaps if the information is very extensive later, it is advisable to create navigation subsections like the proposal made in the Tools section) .
  - Information about the autosave and the default name.
  - Information on the pressure of the Stylus.
  - Information about the configuration of buttons on the mouse and stylus.

- The pertinent changes are made in the 'mkdocs.yml' to reorder the structure.

- The 'toc.integrate' feature is added to 'mkdocs.yml' so that the table of contents is integrated into the navigation menu; giving more space to content and centralizing navigation in a single menu for greater ease.

Needs completing

- 'Autoloading Journals' in the first section of 'Preferences'
- ** tap to select ** configuration and how it works.
- Effect of snapping in the Spiline Drawing tool

2021-01-10 15:20 UTC, rolandlo requested changes
Thank you very much for your contribution. I have made a couple of improvement suggestions. Please look at them and add those you like to your commit (go to "Files Changed" and click on "Add to batch"). If you do not like the suggestion, try to see the point of my suggestion and try to make it better.

2021-01-10 15:20 UTC, rolandlo commented on docs/guide/tools/selecsnap.md
> +Note that in the Grid Snapping description it is mentioned that the grid matches **by default** with the grid background. This caveat is made since in the path mentioned above, by means of the **Grid
```suggestion
Note that in the Grid Snapping description it is mentioned that the grid matches **by default** the grid of the _Graph_ background. This grid consists of squares with side length 0.5 cm. By means of the **Grid size** parameter it is possible to change the side length of the grid squares as a multiple of the original length.
```

2021-01-10 15:20 UTC, rolandlo commented on docs/guide/tools/selecsnap.md
> +In this way, for example, by setting 0.5 in the parameter, the internal grid becomes squares half the size of the grid background, so the objects will try to fit not only the lines of the squares, bu
```suggestion
In this way, for example, by setting 0.5 in the parameter, the internal grid becomes squares half the size of the Graph paper grid background, so the objects will try to fit not only the lines of the squares, but also with its halves.
```

2021-01-10 15:20 UTC, rolandlo commented on docs/guide/config.md
> +Xournal ++ has multiple options that can be configured and customized. Most of these features can be found in the path **Edit> Preferences **.
```suggestion
Xournal ++ has multiple options that can be configured and customized. Most of these features can be found under **Edit > Preferences**.
```

2021-01-10 15:20 UTC, rolandlo commented on docs/guide/config.md
> +### Preassure Sensitivity
```suggestion
### Pressure Sensitivity
```

2021-01-12 05:47 UTC, Wisehh reviewed
Complete

2021-01-12 20:52 UTC, rolandlo commented
Do you know how to squash your commits into one and rebase on current site branch? Here is [some info](https://www.internalpointers.com/post/squash-commits-into-one-git) on that.
Basically (having 2 commits to squash) you need to type
```
git rebase -i HEAD~2
git rebase upstream/site
git push --force
```
After the first command (interactive rebase) you will be put into editor mode where should mark the 2nd commit with `f` (like fixup). Save the file and exit the editor. Then type the other two git commands.

2021-01-17 21:59 UTC, Wisehh commented
Now is the commit ok?

2021-01-19 17:00 UTC, merged

2021-01-19 17:01 UTC, rolandlo commented
Thanks for squashing and rebasing. I merged it.