Update license to new terms
xournalpp/xournalpp.github.io pull request #59
Opened 2021-11-21 21:12 UTC by Technius

Fixes #42

2021-11-21 21:56 UTC, rolandlo reviewed
I have only found one flaw (the hyphen in CC BY-SA 4.0). Otherwise LGTM.

2021-11-21 21:56 UTC, rolandlo commented on LICENSE
> +CC-BY-SA 4.0.
```suggestion
CC BY-SA 4.0.
```
(compare https://creativecommons.org/licenses/by-sa/4.0/)

2021-11-21 23:08 UTC, LittleHuba requested changes
Looks good except for the limitation to specific content of the repository.

2021-11-21 23:08 UTC, LittleHuba commented on LICENSE
> +The website code, configuration, and supporting technical files are licensed
```suggestion
The content of this repository is licensed
```

Keep it as unrestrictive as possible. We don't want to only cover part of the stuff via this license but everything in this repository.

2021-11-23 08:42 UTC, LittleHuba commented
I think it is problematic that we have two separate licenses for the webpage. In my opinion, it is an either-or decision. We should go with CC BY-SA 4.0 for everything.

2021-11-24 08:08 UTC, Technius commented
In general, moving to CC is _more restrictive_ than staying with MIT license. This repository still contains a sizable amount of code, which [CC is not really designed to handle](https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code). The people who are copying/citing the written text will most likely be separate from the people who are copying the code/configuration for use in their own mkdocs setups. CC is quite restrictive for the latter crowd, so I believe we should be treating these crowds differently in terms of license.

2021-11-24 08:21 UTC, LittleHuba commented
Hmm good point. Though for me the situation becomes really awful if we have files that contain both code and text. Those files are not clearly associated with either license. That is a real mess if you want to reuse anything. If we do this, files must be strictly separated and code must be contained within its own directory. Otherwise it is not clear what is covered by what license.

2021-11-24 08:39 UTC, Technius commented
> Though for me the situation becomes really awful if we have files that contain both code and text.

I agree with this, but I don't think this is a very big issue. Most the situations that require code are related to page layout, so we can easily split them into layout code in templates + written text in markdown files. For example, see how the installation page is split into [layout](https://github.com/xournalpp/xournalpp.github.io/tree/site/overrides/installation) and [textual content](https://github.com/xournalpp/xournalpp.github.io/tree/site/docs/installation).

On that note, the home page files could use some refactoring.

2021-11-27 18:25 UTC, Technius commented
Merging in 24 hours unless there are further objections.

2021-12-05 04:15 UTC, Technius commented
Sorry for the delay, was busy this week. Merging now.

2021-12-05 04:15 UTC, merged