Add documentation on the PDF tools
xournalpp/xournalpp.github.io pull request #78
Opened 2022-10-09 07:17 UTC by Technius

Here is some documentation I wrote on:
* Some of the features used for interacting with PDFs
* Pitfalls/subtleties when using annotating PDFs
* The new PDF toolbox and the select PDF text tools

The instructions on "Exporting to PDF" are still WIP.

2022-10-23 03:45 UTC, Technius commented
Merging in 24 hours if there are no objections.

2022-10-23 07:12 UTC, rolandlo requested changes
Overall it looks good to me. Some minor issues are marked (including a wrong link).

2022-10-23 07:12 UTC, rolandlo commented on docs/guide/pdfs.md
> +  the journal will become inconsistent with the actual contents of the (newly
```suggestion
  the journal become inconsistent with the actual contents of the (newly
```

2022-10-23 07:12 UTC, rolandlo commented on docs/guide/tools/pdf_tools.md
> +  underlines the selected text; 3) strikes through the selected text.
It would be nice to see the icons here.

2022-10-23 07:12 UTC, rolandlo commented on docs/guide/pdfs.md
> +
Spaces should be removed from the line.
```suggestion

```

2022-10-23 07:12 UTC, rolandlo commented on docs/guide/pdfs.md
> +
Here as well
```suggestion

```

2022-10-23 07:12 UTC, rolandlo commented on docs/guide/tools/pdf_tools.md
> +
Here as well:
```suggestion

```

2022-10-24 03:39 UTC, rolandlo approved these changes
LGTM

2022-10-31 04:32 UTC, merged